<header class="header">
    <div class="container">
        <div class="header_l">
            <p class="logo">Пассворк</p>
            <p class="title">Коробочная демо-версия</p>
        </div>
    </div>
</header>
<main>
    <div class="form">
        <p class="heading">Демо-версия коробочной версии Пассворк</p>
        <p class="text">Вы можете протестировать основные функции Пассворк на наших серверах.</p>
        <p class="text">Если вы хотите протестировать Пассворк на своем сервере, используйте <a href="https://www.docker.com/">Docker</a>. Инструкцию по установке мы отправили вам в письме. Полноценная версия Пассворк устанавливается без Docker.</p>
        <button class="button" ng-controller="EnterController" ng-click="enter()">Войти</button>
    </div>
</main>
<footer class="footer">
    <div class="container">
        <div class="footer_hold">
            <p class="footer_item">© Passwork 2014–2018</p>
            <p class="footer_item">info@passwork.me</p>
        </div>
    </div>
</footer>